openapi: 3.0.1

info:
  title: ZAY-WAL
  description: "Api Specification for ZAY-WAL"
  version: 1.0.0

servers:
  - url: http://localhost:8000/api/
  - url: https://staging.zaywal.com/api/
  - url: https://api.zaywal.com/

paths:
  /items:
    get:
      summary: Get Items
    parameters:
      - name: page
        in: query
    post:
      summary: Create new Item
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        201:
          content:
            application:/json:
              schema:
                $ref: "#components/schemas/Item"
          description: Successful response code should be 200 with created item
    get:
      summary: Get Items
      responses:
        200:
          description: Array of Items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Item"
  /items/{itemId}:
    get:
      summary: Get Item by ID
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Item"
          description: Item

  /suppliers:
    post:
      summary: Create a supplier
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#components/schemas/Supplier"
            example:
              name: U Ba
              phoneNumber: 09123456789
      responses:
        201:
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Supplier"

  /purchases:
    post:
      summary: Create a purchase
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#components/schemas/Purchase"
      responses:
        201:
          description: Successful Response

  /inventory:
    get:
      summary: Get an inventory
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    category:
                      type: string
                    description:
                      type: string
                    unit:
                      type: string
                    inventory_price_per_unit:
                      type: integer
                    qty:
                      type: integer
                    sale_price_per_unit:
                      type: integer
                    photo:
                      type: string
                      format: url
                example:
                  - id: 1
                    name: ငါးကြင်း
                    category: meat
                    description: ငါးကြင်း
                    unit: ၁၀ သား
                    inventory_price_per_unit: 1800
                    qty: 4
                    sale_price_per_unit: 2000
                    photo: http://url/photos/12312311232
                  - id: 2
                    name: ကန်စွန်းရွက်
                    category: vegetables
                    description: ကန်စွန်းရွက်
                    unit: စည်း
                    inventory_price_per_unit: 200
                    qty: 10
                    sale_price_per_unit: 300
                    photo: http://url/photos/12312312111

  /cart
    post:
      summary: Create a cart
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  
                

          
          
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        photos[]:
          type: array
          items:
            type: string
            format: binary
    Supplier:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        phoneNumber:
          type: number
    Purchase:
      type: object
      properties:
        date: 
          type: string
          format: date
        invoiceNumber:
          type: string
        supplierId:
          type: integer
        items:
          description: Purchased Products
          type: array
          items:
            $ref: "#components/schemas/PurchasedProduct"
    PurchasedProduct:
      type: object
      properties:
        productId:
          type: integer
        price:
          type: integer
        qty:
          type: integer
      




