openapi: 3.0.1

info:
  title: ZAY-WAL
  description: 'Api Specification for ZAY-WAL'
  version: 1.0.0

servers:
- url: http://localhost:8000/v1

paths:
  /item:
    post:
      summary: Create new Item
      requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/Item'
      responses:
          200: 
              content: 
                  application:/json:
                      schema:
                          $ref: '#components/schemas/Item'
              description: Successful resposne code should be 200 with created item

            
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        description:
          type: string
        price: 
          type: integer




