name: Tests

on:
  push:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api-server
    
    services:
      mysql_test_db: 
        image: mysql:8.0
        ports: 
          - 3306:3306
        env:
          MYSQL_DATABASE: api_server_test
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_USER: test
          MYSQL_PASSWORD: "1234"
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
#     - name: Create Database
#       run: |
#         mkdir -p database
#         touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_HOST: 127.0.0.1
      run: vendor/bin/phpunit
      
#   react-tests:
#     runs-on:  ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./web
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js 12.x
#       uses: actions/setup-node@v1
#       with:
#         node-version: 12.x
#     - run: npm ci
#     - run: npm test
